services:
  db:
    image: postgres:15
    container_name: golang_poc
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: auth
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mynetwork

volumes:
  postgres_data:

networks:
  mynetwork:
